name: revolver
version: 1.0.1+1
description: Automatically reloads the application when file changes are detected, much like Nodemon.
author: Keith Elliott <keith.b.elliott@gmail.com>
homepage: https://github.com/techniboogie-dart/revolver
documentation:
executables:
  revolver:
dependencies:
  watcher: '>=0.9.7 <0.10.0'
  args: '>=0.13.3 <0.14.0'
  ansicolor: '>=0.0.9 <0.1.0'
