name: revolver
version: 1.0.0
description: Automatically reloads the application when file changes are detected, much like Nodemon.
author: Keith Elliott
homepage: https://github.com/techniboogie/revolver
documentation:
executables:
  revolver:
dependencies:
  watcher: ^0.9.7
  ansicolor: ^0.0.9
  args: ^0.13.3
